### ISSUE TITLE
ply_reader does not have a function save_model

### ISSUE THREAD

**Issue by xinwang-issaquah** [phermosilla/TotalDenoising#1]
Running GenerateRueMadameDataSet.py gives the following error message:
> Traceback (most recent call last):
>  File "GenerateRueMadameDataSet.py", line 26, in <module>
>    from ply_reader import read_points_binary_ply, save_model
>ImportError: cannot import name 'save_model'

**Comment by phermosilla** [comment]
Thank you for pointing that out. I have just fixed the reference and upload it.
