### ISSUE TITLE
GPUassert: an illegal memory access was encountered sort_gpu.cu 418

### ISSUE THREAD

**Issue by GopiRajuMatta** [phermosilla/TotalDenoising#3]
Hello,

I am getting memory access error while testing the model. With the given dataset, it is working well. But when I gave my data(https://drive.google.com/file/d/1K8o3xGeHG_zMvzFuE3Ed0IX8CMqu-Mk7/view?usp=sharing), it is throwing above error.

Can you please help me out.

Thank you
Gopi

**Comment by milala1235** [comment]
Hello，

I just came into contact with this aspect of learning,and when use train Ruemadame datasets,I am confused about the increase of  loss_Diff.
<img width="1070" alt="截屏2020-12-30 下午12 39 42" src="https://user-images.githubusercontent.com/53614668/103330358-1bff4580-4a9c-11eb-8cd4-e53ee5dd1000.png">
Do you have the same problem? If you have, how do you solve it?

Thank you!

**Comment by phermosilla** [comment]
Hello, the increase of the loss is normal if you are using the L0 loss, since the exponent of the loss decreases linearly from 2 to 0 during training.
