### ISSUE TITLE
need for Synthetic dataset

### ISSUE THREAD

**Issue by eternal-heart** [phermosilla/TotalDenoising#4]
Hello,I'm a student and I'm very interested in your research.Thank you for your code and can you provide me the Synthetic dataset mentioned in your paper? I really need it to do more research.Thank you very much.

**Comment by hyenaku123** [comment]
Hello, have you got the Synthetic dataset mentioned in this paper. I am also a student and need this code very much. If you have this, can you send it to my email. Thank you very much. email:hyenaku@163.com

**Comment by hyenaku123** [comment]
> Hello,I'm a student and I'm very interested in your research.Thank you for your code and can you provide me the Synthetic dataset mentioned in your paper? I really need it to do more research.Thank you very much.

Hello, have you got the Synthetic dataset mentioned in this paper. I am also a student and need this code very much. If you have this, can you send it to my email. Thank you very much. email:hyenaku@163.com

**Comment by phermosilla** [comment]
You can download the synthetic data set from this link: https://drive.google.com/file/d/1-r1yO4y2X0q64ZbdLdFGnUcuEWMo5ZF2
